import type { CharacterSprites, PixelFrame } from '../../types'

const S_IDLE_1: PixelFrame = [
  '......ihhhi.....',
  '.....ihhhhhi....',
  '....ihhdhhhhi...',
  '....ihgggghi....',
  '....ihgggghi....',
  '....ishssshi....',
  '....issssssi....',
  '....ibsisisbi...',
  '....ibbsssbbi...',
  '.....ibbbbbi....',
  '......issi......',
  '....ijjjjjji....',
  '...ijjwwwwjji...',
  '..ikjwwwwwwjki..',
  '..ikjwwwwwwjki..',
  '..iksjwwwwjski..',
  '...iijjjjjjii...',
  '.....ippppi.....',
  '.....ippppi.....',
  '.....ippippi....',
  '.....ipi.ipi....',
  '.....ipi.ipi....',
  '....iooi.iooi...',
  '....iooi.iooi...',
]

const S_IDLE_2: PixelFrame = [
  '................',
  '......ihhhi.....',
  '.....ihhhhhi....',
  '....ihhdhhhhi...',
  '....ihgggghi....',
  '....ihgggghi....',
  '....ishssshi....',
  '....issssssi....',
  '....ibsisisbi...',
  '....ibbsssbbi...',
  '.....ibbbbbi....',
  '....ijjjjjji....',
  '...ijjwwwwjji...',
  '..ikjwwwwwwjki..',
  '..ikjwwwwwwjki..',
  '..iksjwwwwjski..',
  '...iijjjjjjii...',
  '.....ippppi.....',
  '.....ippppi.....',
  '.....ippippi....',
  '.....ipi.ipi....',
  '.....ipi.ipi....',
  '....iooi.iooi...',
  '....iooi.iooi...',
]

const S_WALK_1: PixelFrame = [
  '......ihhhi.....',
  '.....ihhhhhi....',
  '....ihhdhhhhi...',
  '....ihgggghi....',
  '....ihgggghi....',
  '....ishssshi....',
  '....issssssi....',
  '....ibsisisbi...',
  '....ibbsssbbi...',
  '.....ibbbbbi....',
  '......issi......',
  '....ijjjjjji....',
  '...ijjwwwwjji...',
  '..ikjwwwwwwjki..',
  '..ikjwwwwwwjki..',
  '..iksjwwwwjski..',
  '...iijjjjjjii...',
  '.....ippppi.....',
  '.....ippppi.....',
  '....ippippi.....',
  '....ipi.ippi....',
  '...ipi...ipi....',
  '..iooi...iooi...',
  '..iooi....ioi...',
]

const S_WALK_2: PixelFrame = [
  '......ihhhi.....',
  '.....ihhhhhi....',
  '....ihhdhhhhi...',
  '....ihgggghi....',
  '....ihgggghi....',
  '....ishssshi....',
  '....issssssi....',
  '....ibsisisbi...',
  '....ibbsssbbi...',
  '.....ibbbbbi....',
  '......issi......',
  '....ijjjjjji....',
  '...ijjwwwwjji...',
  '..ikjwwwwwwjki..',
  '..ikjwwwwwwjki..',
  '..iksjwwwwjski..',
  '...iijjjjjjii...',
  '.....ippppi.....',
  '.....ippppi.....',
  '.....ippippi....',
  '.....ipi.ipi....',
  '.....ipi.ipi....',
  '....iooi.iooi...',
  '....iooi.iooi...',
]

const S_WALK_3: PixelFrame = [
  '......ihhhi.....',
  '.....ihhhhhi....',
  '....ihhdhhhhi...',
  '....ihgggghi....',
  '....ihgggghi....',
  '....ishssshi....',
  '....issssssi....',
  '....ibsisisbi...',
  '....ibbsssbbi...',
  '.....ibbbbbi....',
  '......issi......',
  '....ijjjjjji....',
  '...ijjwwwwjji...',
  '..ikjwwwwwwjki..',
  '..ikjwwwwwwjki..',
  '..iksjwwwwjski..',
  '...iijjjjjjii...',
  '.....ippppi.....',
  '.....ippppi.....',
  '.....ippippi....',
  '....ippi.ipi....',
  '....ipi...ipi...',
  '...iooi...iooi..',
  '...ioi....iooi..',
]

const S_WALK_4: PixelFrame = [
  '......ihhhi.....',
  '.....ihhhhhi....',
  '....ihhdhhhhi...',
  '....ihgggghi....',
  '....ihgggghi....',
  '....ishssshi....',
  '....issssssi....',
  '....ibsisisbi...',
  '....ibbsssbbi...',
  '.....ibbbbbi....',
  '......issi......',
  '....ijjjjjji....',
  '...ijjwwwwjji...',
  '..ikjwwwwwwjki..',
  '..ikjwwwwwwjki..',
  '..iksjwwwwjski..',
  '...iijjjjjjii...',
  '.....ippppi.....',
  '.....ippppi.....',
  '.....ippippi....',
  '.....ipi.ipi....',
  '.....ipi.ipi....',
  '....iooi.iooi...',
  '....iooi.iooi...',
]

const S_JUMP_1: PixelFrame = [
  '......ihhhi.....',
  '.....ihhhhhi....',
  '....ihhdhhhhi...',
  '....ihgggghi....',
  '....ihgggghi....',
  '....ishssshi....',
  '....issssssi....',
  '....ibsisisbi...',
  '....ibbsssbbi...',
  '.....ibbbbbi....',
  '......issi......',
  '....ijjjjjji....',
  '...ijjwwwwjji...',
  '..ikjwwwwwwjki..',
  '..ikjwwwwwwjki..',
  '..iksjwwwwjski..',
  '...iijjjjjjii...',
  '.....ippppi.....',
  '.....ippppi.....',
  '.....ippppi.....',
  '....iooi.iooi...',
  '....iooi.iooi...',
  '....iooi.iooi...',
  '....iooi.iooi...',
]

const S_JUMP_2: PixelFrame = [
  '......ihhhi.....',
  '.....ihhhhhi....',
  '....ihhdhhhhi...',
  '....ihgggghi....',
  '....ihgggghi....',
  '....ishssshi....',
  '....issssssi....',
  '....ibsisisbi...',
  '....ibbsssbbi...',
  '.....ibbbbbi....',
  '......issi......',
  '....ijjjjjji....',
  '...ijjwwwwjji...',
  '..ikjwwwwwwjki..',
  '..ikjwwwwwwjki..',
  '..iksjwwwwjski..',
  '...iijjjjjjii...',
  '.....ippppi.....',
  '....ipppppi.....',
  '....ipppppi.....',
  '.....ippppi.....',
  '......ippi......',
  '......ippi......',
  '................',
]

const S_JUMP_3: PixelFrame = [
  '................',
  '................',
  '......ihhhi.....',
  '.....ihhhhhi....',
  '....ihhdhhhhi...',
  '....ihgggghi....',
  '....ihgggghi....',
  '....ishssshi....',
  '....issssssi....',
  '....ibsisisbi...',
  '....ibbsssbbi...',
  '.....ibbbbbi....',
  '...ijjwwwwjji...',
  '..ikjwwwwwwjki..',
  '..ikjwwwwwwjki..',
  '..iksjwwwwjski..',
  '...iijjjjjjii...',
  '.....ippppi.....',
  '....ipppppi.....',
  '...ippi..ippi...',
  '..ipi......ipi..',
  '..ipi......ipi..',
  '.ioi........ioi.',
  '.ioi........ioi.',
]

const S_SKID_1: PixelFrame = [
  '.....ihhhi......',
  '....ihhhhhi.....',
  '...ihhdhhhhi....',
  '....ihgggghi....',
  '....ihgggghi....',
  '....ishssshi....',
  '....issssssi....',
  '....ibsisisbi...',
  '....ibbsssbbi...',
  '.....ibbbbbi....',
  '......issi......',
  '....ijjjjjji....',
  '...ijjwwwwjji...',
  '..ikjwwwwwwjki..',
  '..ikjwwwwwwjki..',
  '..ikjjwwwwjsski.',
  '...iijjjjjjii...',
  '.....ippppi.....',
  '.....ippppi.....',
  '.....ippippi....',
  '.....ipi.ipi....',
  '.....ipi.ipi....',
  '....iooi.iooi...',
  '....iooi.iooi...',
]

export const dylanSprites: CharacterSprites = {
  palette: {
    h: '#6b4a2f', d: '#4e3521', s: '#f2c9a0', b: '#8a5a34', g: '#c9a13b',
    j: '#3f6d3f', k: '#2c4f2c', w: '#f4f1e8', p: '#3d5a80', o: '#2b2b2b',
    i: '#201a17',
  },
  frameWidth: 16,
  frameHeight: 24,
  directions: {
    S: { idle: [S_IDLE_1, S_IDLE_2], walk: [S_WALK_1, S_WALK_2, S_WALK_3, S_WALK_4], jump: [S_JUMP_1, S_JUMP_2, S_JUMP_3], skid: [S_SKID_1] },
    SW: { idle: [], walk: [], jump: [], skid: [] }, // authored in Task 12
    W: { idle: [], walk: [], jump: [], skid: [] },
    NW: { idle: [], walk: [], jump: [], skid: [] },
    N: { idle: [], walk: [], jump: [], skid: [] },
  },
}

if (import.meta.env.DEV) {
  for (const [d, set] of Object.entries(dylanSprites.directions))
    for (const [a, frames] of Object.entries(set))
      (frames as PixelFrame[]).forEach((f: PixelFrame, i: number) => {
        if (f.length !== 24 || f.some((r: string) => r.length !== 16))
          throw new Error(`bad frame ${d}/${a}[${i}]`)
      })
}
